# Q1.2: Multi-Output Perceptron (Single Weight Matrix)

Train one perceptron model with a **2×2 weight matrix** to produce AND and OR outputs simultaneously.

**Exam outputs:** final weight matrix, biases, and predicted outputs/truth table.

## Step 1: Import Libraries

In [1]:
import numpy as np

## Step 2: Define Step Activation Function

In [2]:
def step(x):
    return np.where(x >= 0, 1, 0)

## Step 3: Train Multi-Output Perceptron

### Define Training Function

In [3]:
def train_multi_perceptron(X, Y, lr=0.1, epochs=20):
    # W: weight matrix [input_features, num_outputs]
    # Y: [samples, num_outputs]
    W = np.zeros((X.shape[1], Y.shape[1]))
    b = np.zeros(Y.shape[1])
    
    for epoch in range(epochs):
        for i in range(len(X)):
            z = np.dot(X[i], W) + b
            y_pred = step(z)
            error = Y[i] - y_pred
            # Update weights and bias for all outputs
            W += lr * np.outer(X[i], error)
            b += lr * error
    
    return W, b

## Step 4: Prepare Data for AND and OR Gates

### Define Input and Multi-Output Targets

In [4]:
# Input: x1, x2
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Multi-output targets: [AND, OR]
Y = np.array([
    [0, 0],  # AND(0,0)=0, OR(0,0)=0
    [0, 1],  # AND(0,1)=0, OR(0,1)=1
    [0, 1],  # AND(1,0)=0, OR(1,0)=1
    [1, 1]   # AND(1,1)=1, OR(1,1)=1
])

print("Input X:")
print(X)
print("\nTarget Y [AND, OR]:")
print(Y)

Input X:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Target Y [AND, OR]:
[[0 0]
 [0 1]
 [0 1]
 [1 1]]


## Step 5: Train the Multi-Output Perceptron

In [5]:
W, b = train_multi_perceptron(X, Y)

print("Weight Matrix W:")
print(W)
print(f"Shape: {W.shape}")
print("\nBias Vector b:")
print(b)
print(f"Shape: {b.shape}")

Weight Matrix W:
[[0.2 0.1]
 [0.1 0.1]]
Shape: (2, 2)

Bias Vector b:
[-0.2 -0.1]
Shape: (2,)


## Step 6: Test and Display Results

### Generate Predictions

In [6]:
predictions = []
for i in range(len(X)):
    z = np.dot(X[i], W) + b
    y_pred = step(z)
    predictions.append(y_pred)

predictions = np.array(predictions)

### Display Truth Table

In [7]:
print("\nMulti-Output Perceptron Truth Table:")
print("x1  x2  | AND (Predicted) | OR (Predicted)")
print("----------------------------------------------")
for i in range(len(X)):
    print(f" {X[i][0]}   {X[i][1]}  |        {predictions[i][0]}        |       {predictions[i][1]}")


Multi-Output Perceptron Truth Table:
x1  x2  | AND (Predicted) | OR (Predicted)
----------------------------------------------
 0   0  |        0        |       0
 0   1  |        0        |       1
 1   0  |        0        |       1
 1   1  |        1        |       1


### Verify Correctness

In [8]:
accuracy_and = np.mean(predictions[:, 0] == Y[:, 0]) * 100
accuracy_or = np.mean(predictions[:, 1] == Y[:, 1]) * 100

print(f"\nAND Gate Accuracy: {accuracy_and}%")
print(f"OR Gate Accuracy: {accuracy_or}%")


AND Gate Accuracy: 100.0%
OR Gate Accuracy: 100.0%


## Summary

**Key Observations:**
- Single weight matrix **W** (shape [2, 2]) handles both gates
- Single bias vector **b** (shape [2])
- One forward pass produces both AND and OR outputs simultaneously
- More efficient than training separate perceptrons